### ISSUE TITLE
ACCEPTED: [FR] tapping USDHEX price could a chart.

### ISSUE THREAD

**Issue by discochuck** [gruvin/hexmob.win#4]
It might be useful for users, if the current price of hex to be clickable and for that to pull up the hexusd(c,t)?

**Comment by gruvin** [comment]
thanks for the idea ... can you explain further what you mean by, "pull up the hexusd..."? Like, a chart?

**Comment by discochuck** [comment]
Yep! Something like dex.vision perhaps? Or I guess it could link to hexusdc/t on tv or something within nomics(not sure what kind of interactive charts they might have)?

**Comment by gruvin** [comment]
OK. Cool. Added to my list. Could be a while but as a user request, it should end up happening sooner than later.

Meanwhile, there is already a built-in "Stats" section, with a couple of very basic HEX and TShare rate charts.
