### ISSUE TITLE
New feature (unless it's already there): theme selector

### ISSUE THREAD

**Issue by discochuck** [gruvin/hexmob.win#6]
I saw in the source there are a few css's. Is there a
 ?style=whatever feature?

**Comment by gruvin** [comment]
Nope.

Out of interest, are you using hexmob.win or go.tshare.app?

One thing I noticed only recently, somehow, is the the font used for numeric output isn't actually monospace.

The color schemes ... well those speak for themselves, I suppose.  This thing wasn't actually designed with the idea that any but myself and maybe a couple friends would use it, back when HEX was under 0.1c. In any case, I did have a go at a light theme -- whit background etc. Failed miserably. The use of expanding accordions makes keeping the various parts contrasty enough to not utterly confuse the user's brain, well, challenging.

With all that in mind, I have many time thought of re-doing the whole UI from scratch, without the accordions and more sort of traditional. That however received push-back from community and no real comment besides. LOL

That and I'm insanely busy doing other stuff.

Any comments? :P

**Comment by discochuck** [comment]
That was hexmob.win, with ssl error. I usually use tshare but wanted to give ya a heads up in case you used the site for anything else. 

I dig the 🪗 vibe and the layout. Was just wandering if there might be anymore hidden features buried in there. 

I was going to git clone and do a grep -rf to see what else might be I there but figured I'd just ask about the theming.

Thanks again for all your work on this. It's a really great tool.

**Comment by gruvin** [comment]
All good. 

Thanks for the heads up -- those are much appreciated, especially when you had to go through the whole secure email setup, presumably. (Still having trouble with the ssl cert. The automatic system clearly failed and manually prodding it hasn't helps. Cert stuck in pending for three days. Have ordered from two additional separate suppliers now. Something upstream they all use must be down or who knows.)

You're in luck! On the off chance that you ever played about with Tewkenaire and have stakes there (HEX2, (could add HEX3) HEX4 or HEX5), you can also add ```?tewkenaire``` (or ```&tewkenaire```) to see those ... though only related to the connected wallet.

Last one is ```?closed```, which prevent the Active Stakes section from auto opening. I use it alongside ```?account=```.

Full bling example ...

```https://go.tshare.app/?closed&tewkenaire&account=0x1234....5678:LAMBO```
