### ISSUE TITLE
when manually switching dates via input from clicking on time map or changing end date range 

### ISSUE THREAD

**Issue by discochuck** [gruvin/hexmob.win#7]
It seems like to get the system to register a change in date after the initial usage of the drop down end date box, you have to set the end date period twice. 

like if I set it to 1 year from the get go, see the results and decide to switch to 2 years. Most of the fields update, however the actualy mm/dd/year field does not. 

not sure if that actually effects the input to the contract or if it's just visual.

**Comment by gruvin** [comment]
Thanks. Investigating. Will advise back here.

**Comment by gruvin** [comment]
Hmmm. Unable to reproduce ... though it did reveal a minor bug with the spinning "hurry up and wait" HEXglobe thing appearing when it shouldn't sometimes.

The current version is 0.2.55B (upper right corner) not that anything here has changed for quite some time.

**Comment by gruvin** [comment]
Oh and no, the only field that matter for the contract send is the days input field itself. ;-)

**Comment by discochuck** [comment]
gg man

**Comment by gruvin** [comment]
Seems this was in fact a bug but didn't always occur. Cause was a timing race condition between the code that waits for day number changes for graph updates versus calculating bonuses.  I'm deploying the fix just now.
