### ISSUE TITLE
Feature request: usd ( or whatever ) value of Interest

### ISSUE THREAD

**Issue by discochuck** [gruvin/hexmob.win#9]
When you're looking at an account it'd be neat to see the dollar value of the interest accrued.

**Comment by gruvin** [comment]
Do you mean in the overall summary for that account?

Interest USD is shown under the END STAKE button within each stake,
presently.

I'm sure I've said it before but just for the record, I'm (still) jittery
about showing USD values for anything. Too many middlemen just to get the
exchange rate. :P

**Comment by discochuck** [comment]
Right on. Closed
